[tool.poetry]
name = "coursework4"
version = "0.1.0"
description = ""
authors = ["cniimf_ot <ot@cniimf.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
